### ISSUE TITLE
Conflict between VS2015 NuGet and PowerShell provider

### ISSUE THREAD

**Issue by mjyeaney** [PowerShell/PowerShellGetv2#107]
Cross-posted from OneGet repo issue here: [https://github.com/OneGet/oneget/issues/274](https://github.com/OneGet/oneget/issues/274)

VS Environment:
```
VS2015 Community, v.14.0.25431.01, Update 3
NuGet Package Manager for VS2015, v.3.5.0.1484
```

Powershell Environment:
```
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Powershell Package Providers:
```
NuGet Provider, v.2.8.5.208
PowerShellGet, v.1.1.2.0
```

Package Source Locations:
```
nuget.org - https://api.nuget.org/v3/index.json
PSGallery - https://www.powershellgallery.com/api/v2/
```

Given the above configuration, VS2015 is able to browse NuGet packages without issue. PowerShell, however, is unable to search the NuGet repositories due to incorrect location URL (api v3). This results in the following HTTP trace when executing `Find-Package` from a PowerShell Session:

![fiddler-error](https://cloud.githubusercontent.com/assets/1410150/24296344/1ebbca56-1075-11e7-8558-6ce7ea6ea5dc.png)

(**Sidenote** - what's with the request for "Foobar" to the Powershell Gallery?)

Now, change the NuGet location in for the PowerShell NuGet provider to the correct api v2 and restart the PowerShell session:

``Set-PackageSource -name nuget-org -NewLocation https://www.nuget.org/api/v2``

PowerShell is now able to search NuGet repositories correctly - but note that VS2015 (after restart) is now broken:
```
[nuget.org] Unable to load the service index for source https://www.nuget.org/api/v2.
  The content at 'https://www.nuget.org/api/v2' is not a valid JSON object.
  Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
```
![vs-nuget-error](https://cloud.githubusercontent.com/assets/1410150/24296356/2a5d0b86-1075-11e7-9e1e-783aa6419cd1.png)

While I'm aware OneGet doesn't currently support the NuGet API v3, it seems unexpected that it would break other applications (i.e., VS).

**Comment by bmanikm** [comment]
@mjyeaney From the above details, it doesn't look like PowerShellGet related issue. PowerShellGet provider doesn't update the NuGet source registrations.

Are you using the PowerShellGet provider or NuGet provider? 
Is it possible to get the verbose and debug messages from Find-Package?

**Comment by mjyeaney** [comment]
Thanks for the feedback, @bmanikm. I'm honestly not sure what the _real_ issue is, hence the cross posting. Apologies for the confusion.

As for the verbose tracing - the dump is shown below. Note that it appears after the internal exception is thrown, Fiddler is showing the traces for 'FoooBar' to the PowerShellGallery (which I don't see in the trace). 

Is this expected behavior?

```
00:00:00.0000009 Calling 'msi::GetDynamicOptions' 'Provider'
00:00:00.0098298 Calling 'msi::GetDynamicOptions' 'Source'
00:00:00.0185772 Calling 'msi::GetDynamicOptions' 'Package'
00:00:00.0494775 Calling 'msu::GetDynamicOptions' 'Provider'
00:00:00.0569915 Calling 'msu::GetDynamicOptions' 'Source'
00:00:00.0658850 Calling 'msu::GetDynamicOptions' 'Package'
00:00:00.0735907 Calling 'Programs::GetDynamicOptions' 'Provider'
00:00:00.0815558 Calling 'Programs::GetDynamicOptions' 'Source'
00:00:00.0892157 Calling 'Programs::GetDynamicOptions' 'Package'
00:00:00.0983920 Calling New() : MethodName = 'GetDynamicOptions'
00:00:00.0984419 Verbose: True
00:00:00.0984731 Debug: True
00:00:00.0985025 Name: FSharp.Charting
00:00:00.0996875 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
00:00:00.1008445 In PowerShellGet Provider - 'Get-DynamicOptions'.
00:00:00.1026533 Done calling powershell «Get-DynamicOptions» «PSModule»
00:00:00.1079801 Calling New() : MethodName = 'GetDynamicOptions'
00:00:00.1080128 Verbose: True
00:00:00.1080328 Debug: True
00:00:00.1080520 Name: FSharp.Charting
00:00:00.1088861 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
00:00:00.1097305 In PowerShellGet Provider - 'Get-DynamicOptions'.
00:00:00.1121649 Done calling powershell «Get-DynamicOptions» «PSModule»
00:00:00.1184006 Calling New() : MethodName = 'GetDynamicOptions'
00:00:00.1184328 Verbose: True
00:00:00.1184533 Debug: True
00:00:00.1184724 Name: FSharp.Charting
00:00:00.1192632 INVOKING PowerShell Fn Get-DynamicOptions with args Package that has length 1
00:00:00.1200628 In PowerShellGet Provider - 'Get-DynamicOptions'.
00:00:00.1238478 Done calling powershell «Get-DynamicOptions» «PSModule»
00:00:00.9403091 Calling SearchForPackages. Name='FSharp.Charting'
Using the provider 'msi' for searching packages.
00:00:00.9411610 PackageProvider::FindPackage with name FSharp.Charting
Using the provider 'NuGet' for searching packages.
00:00:00.9423726 PackageProvider::FindPackage with name FSharp.Charting
Using the provider 'msu' for searching packages.
00:00:00.9462060 PackageProvider::FindPackage with name FSharp.Charting
Using the provider 'Programs' for searching packages.
00:00:00.9475086 Calling 'NuGet'::'FindPackage' - name='FSharp.Charting', requiredVersion='',minimumVersion='', maximumVersion='''.
00:00:00.9475529 Iterating 'FSharp.Charting'.
00:00:00.9476686 There are '1' registered sources in 'NuGet' provider.
00:00:00.9477064 nuget.org
00:00:00.9477391 Calling 'NuGetRequest'::'GetPackageById', 'FSharp.Charting'.
00:00:00.9477839 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'FSharp.Charting'.
00:00:00.9478188 Calling 'NuGetClient'::'FindPackage'.
Searching repository 'https://api.nuget.org/v3/index.json/FindPackagesById()?id='FSharp.Charting'' for ''.
00:00:00.9496453 Downloading 'https://api.nuget.org/v3/index.json/FindPackagesById()?id='FSharp.Charting'&$skip=0&$top=40'.
00:00:00.9500526 PackageProvider::FindPackage with name FSharp.Charting
Using the provider 'PowerShellGet' for searching packages.
00:00:00.9516243 PackageProvider::FindPackage with name FSharp.Charting
00:00:00.9519528 Calling SearchForPackages After Select 5
00:00:00.9580867 Calling New() : MethodName = 'FindPackage'
00:00:00.9581591 Verbose: True
00:00:00.9581954 Debug: True
00:00:00.9582267 Name: FSharp.Charting
00:00:00.9591019 INVOKING PowerShell Fn Find-Package with args System.String[], , ,  that has length 4
00:00:00.9603289 In PowerShellGet Provider - 'Find-Package'.
00:00:00.9608383 OPTION: Verbose => True
00:00:00.9613483 OPTION: Debug => True
00:00:00.9615535 OPTION: Name => FSharp.Charting
The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
Getting the provider object for the PackageManagement Provider 'NuGet'.
The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is 'NuGet'.
00:00:00.9673959 PackageProvider::FindPackage with name FSharp.Charting
00:00:00.9725091 Calling 'NuGet'::'FindPackage' - name='FSharp.Charting', requiredVersion='',minimumVersion='', maximumVersion='''.
00:00:00.9725553 Iterating 'FSharp.Charting'.
00:00:00.9726938 There are '1' registered sources in 'NuGet' provider.
00:00:00.9727559 Source 'https://www.powershellgallery.com/api/v2/' is not one of the registered sources in 'NuGet' provider.
00:00:01.3384174 Completed downloading 'https://api.nuget.org/v3/index.json/FindPackagesById()?id='FSharp.Charting'&$skip=0&$top=40'.
00:00:01.3414074 System.AggregateException: One or more errors occurred. ---> System.Xml.XmlException: Data at the root level is invalid. Line 1, 
position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at Microsoft.PackageManagement.Provider.Utility.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   at Microsoft.PackageManagement.NuGetProvider.HttpClientPackageRepository.<SendRequest>d__10.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Parallel.SelectManyQueryOperator`3.SelectManyQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, Pair`2& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at Microsoft.PackageManagement.NuGetProvider.NuGetRequest.YieldPackages(IEnumerable`1 packageReferences, String searchKey)
   at Microsoft.PackageManagement.NuGetProvider.NuGetProvider.FindPackage(String name, String requiredVersion, String minimumVersion, String 
maximumVersion, Int32 id, NuGetRequest request)
---> (Inner Exception #0) System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at Microsoft.PackageManagement.Provider.Utility.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   at Microsoft.PackageManagement.NuGetProvider.HttpClientPackageRepository.<SendRequest>d__10.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Parallel.SelectManyQueryOperator`3.SelectManyQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, Pair`2& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()<---

00:00:01.6438170 Source 'https://www.powershellgallery.com/api/v2/' is validated.
00:00:01.6440628 Calling 'NuGetRequest'::'GetPackageById', 'FSharp.Charting'.
00:00:01.9947617 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'FSharp.Charting'.
00:00:01.9949334 Calling 'NuGetClient'::'FindPackage'.
Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='FSharp.Charting'' for ''.
00:00:01.9952119 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='FSharp.Charting'&$skip=0&$top=40'.
00:00:02.2974960 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='FSharp.Charting'&$skip=0&$top=40'.
00:00:02.2976906 '0' packages received in the last request.
Total package yield:'0' for the specified package 'FSharp.Charting'.
00:00:02.2978422 Completed iterating for 'FSharp.Charting'.
00:00:02.2980619 PowerShell Script 'PSModule' Function 'Find-Package' returns null.
00:00:02.2988774 Done calling powershell «Find-Package» «PSModule»
00:00:02.3114374 unmatched package name='FSharp.Charting'
find-package : No match was found for the specified search criteria and package name 'FSharp.Charting'. Try Get-PackageSource to see all available 
registered package sources.
At line:1 char:1
+ find-package FSharp.Charting -verbose -Debug *>&1 | tee output.log
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage
 ```

**Comment by bmanikm** [comment]
From above messages, it is related to NuGet provider.  Regarding 'FoooBarr' search, NuGet provider uses this search term to check whether the specified/registered source is available or not.

By default, OneGet queries all the loaded providers. Consider using -Provider and -Source parameters on Find-Package.
```powershell
Find-Package -Name FSharp.Charting -Provider NuGet -Source nuget.org -Verbose -Debug
```

**Comment by mjyeaney** [comment]
Perfect - thanks for the follow-up.
