### ISSUE TITLE
Install-Module throw a ParameterBindingException

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShellGetv2#11]
I use this code in a server 2012 (new VM on Azure) : 

``` Powershell
Install-PackageProvider Nuget -ForceBootstrap -Force
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

Install-module PowershellGet -MinimumVersion 1.1.0.0 -Force
 Remove-module PowershellGet
 Remove-module PackageManagement  
Import-Module PowershellGet 

$ModuleVersion= (Get-module PowershellGet).Version
Write-warning "version= $ModuleVersion"   

$c=gcm PackageManagement\Install-Package
$c.Parameters.GetEnumerator()|? {$_.Key -match '^S'}

PowershellGet\Install-Module -Name 'PSScriptAnalyzer' -Repository PSGallery -Scope AllUsers -Force -SkipPublisherCheck
```

The last statement throw a **_ParameterBindingException_** (NamedParameterNotFound) :
![bug-packagemanagement-server2012](https://cloud.githubusercontent.com/assets/4894452/19320608/3e7c4ed0-90b2-11e6-8db7-0f3e57eafb72.png)

The _SkipPublisherCheck_ parameter is missing.

``` Powershell
PS C:\Users\laurent> $error[0]|select *
PSMessageDetails      :
Exception             : System.Management.Automation.ParameterBindingException: A parameter cannot be found that
                        matches parameter name 'SkipPublisherCheck'.
                           at
                        System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                        input, Hashtable errorResults, Boolean enumerate)
                           at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean
                        ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts,
                        CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame
                        frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
TargetObject          :
CategoryInfo          : InvalidArgument: (:) [Install-Package], ParameterBindingException
FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Install-Module<Process>, C:\Program
                        Files\WindowsPowerShell\Modules\PowershellGet\1.1.0.0\PSModule.psm1: line 1800
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}



PS C:\Users\laurent> $StackTrace
   at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException or
iginalBindingException)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 ar
guments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorR
esults, Boolean enumerate)
```

**Comment by bmanikm** [comment]
You need to run below command to load the latest version of PowerShellGet provider or launch a new PowerShell Session. 

``` powershell
Import-PackageProvider PowerShellGet -Force
```

We recommend launching a new PowerShell Session as mentioned in [PowerShellGet and PackageManagement in PowerShell Gallery and GitHub](https://blogs.msdn.microsoft.com/powershell/2016/09/29/powershellget-and-packagemanagement-in-powershell-gallery-and-github/)
