### ISSUE TITLE
PSGet broken on my Mac - PSCore up to alpha14

### ISSUE THREAD

**Issue by apetitjean** [PowerShell/PowerShellGetv2#80]
PowerShellGet (with PSCore alpha11, 12, 14) never worked on my MacOS (10.12). 

Is it because of my locale which is Fr-fr?

## Current Behavior

Tryed on Alpha14 and previous versions without installing or updating additional modules and it never worked.

There's no package source registered, nor repositories. So PowerShell is not able to find or install any module from the PowerShell Gallery.

## Possible Solution

I have no clue...

## Steps to Reproduce (for bugs)

1. 
```PowerShell
PS /Users/admin> Get-PackageSource                                                                                                                                              
WARNING: Unable to find package sources.

PS /Users/admin> Get-PSRepository                                                                                                                                               
WARNING: Unable to find module repositories.

PS /Users/admin> Register-PackageSource -Name PSGallery -Location 'https://www.powershellgallery.com/api/v2/' -ProviderName PowerShellGet -Trusted                              
Register-PackageSource : The PSGallery repository has pre-defined locations. The 'Location, NewLocation or SourceLocation' parameter is not allowed, try again after removing
the 'Location, NewLocation or SourceLocation' parameter.
At line:1 char:1
+ Register-PackageSource -Name PSGallery -Location 'https://www.powersh ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (https://www.pow...ery.com/api/v2/:String) [Register-PackageSource], Exception
    + FullyQualifiedErrorId : ParameterIsNotAllowedWithPSGallery,Add-PackageSource,Microsoft.PowerShell.PackageManagement.Cmdlets.RegisterPackageSource
 
PS /Users/admin> Register-PackageSource -Name PSGallery2 -Location 'https://www.powershellgallery.com/api/v2/' -ProviderName PowerShellGet -Trusted                             
Register-PackageSource : The specified Uri 'https://www.powershellgallery.com/api/v2/' for parameter 'Location' is an invalid Web Uri. Please ensure that it meets the Web Uri
requirements.
At line:1 char:1
+ Register-PackageSource -Name PSGallery2 -Location 'https://www.powers ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (https://www.pow...ery.com/api/v2/:String) [Register-PackageSource], Exception
    + FullyQualifiedErrorId : InvalidWebUri,Add-PackageSource,Microsoft.PowerShell.PackageManagement.Cmdlets.RegisterPackageSource
```
2.
```PowerShell
PS /Users/admin> Invoke-RestMethod -Uri "https://www.powershellgallery.com/api/v2/Packages()?&`$skip=80&`$top=40" -Verbose                                                       
Invoke-RestMethod : The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
At line:1 char:1
+ Invoke-RestMethod -Uri "https://www.powershellgallery.com/api/v2/Pack ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
 
PS /Users/admin> Find-Package -Provider NuGet -Source https://www.powershellgallery.com/api/v2/ -Name Pester -Verbose -Debug                                                     
DEBUG: 00:00:00.0000003 Calling 'NuGet'::'ResolvePackageSources'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): 
DEBUG: 00:00:00.0002842 There are '0' registered sources in 'NuGet' provider.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 00:00:00.0013981 Source 'https://www.powershellgallery.com/api/v2/' is not one of the registered sources in 'NuGet' provider.
DEBUG: 00:00:00.0473851 System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: 
The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> 
System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 
'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.CryptoInitializer.Initialize()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.HttpInitializer.Initialize()
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at Microsoft.PackageManagement.Provider.Utility.PathUtility.GetHttpClientHelper(String username, SecureString password, IWebProxy webProxy) in 
C:\projects\oneget\src\Microsoft.PackageManagement\providers\inbox\Common\Utility\PathUtility.cs:line 220
   at Microsoft.PackageManagement.NuGetProvider.NuGetRequest.get_ClientWithoutAcceptHeader() in 
C:\projects\oneget\src\Microsoft.PackageManagement.NuGetProvider\NugetLightRequest.cs:line 711
   at Microsoft.PackageManagement.NuGetProvider.NuGetPathUtility.ValidateUri(Uri query, NuGetRequest request)
Find-Package : Unable to find package source 'https://www.powershellgallery.com/api/v2/'. Use Get-PackageSource to see all available package sources.in 
At line:1 char:1et\src\Microsoft.PackageManagement.NuGetProvider\Utility\NuGetPathUtility.cs:line 63
+ Find-Package -Provider NuGet -Source https://www.powershellgallery.co ...ources>d__63.MoveNext() in 
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ightRequest.cs:line 1207
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exception
    + FullyQualifiedErrorId : SourceNotFound,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage
 onfirm
Invoke-RestMethod : The type initializer for 'System.Net.Http.CurlHandler' threw an exception.ce to see all available package sources.
At line:1 char:1 to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
+ Invoke-RestMethod -Uri "https://www.powershellgallery.com/api/v2/Pack ....com/api/v2/'. Use Get-PackageSource to see all available package sources.
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exception
Register-PackageSource : The specified Uri 'https://www.powershellgallery.com/api/v2/' for parameter 'Location' is an invalid Web Uri. Please ensure that it meets the Web Uri 
requirements.
At line:1 char:1                                                                                                                                                                 
+ Register-PackageSource -Name PSGallery2 -Location 'https://www.powers ...                                                                                                      + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (https://www.pow...ery.com/api/v2/:String) [Register-PackageSource], Exception
    + FullyQualifiedErrorId : InvalidWebUri,Add-PackageSource,Microsoft.PowerShell.PackageManagement.Cmdlets.RegisterPackageSource
 
Register-PackageSource : The PSGallery repository has pre-defined locations. The 'Location, NewLocation or SourceLocation' parameter is not allowed, try again after removing 
the 'Location, NewLocation or SourceLocation' parameter.
At line:1 char:1
+ Register-PackageSource -Name PSGallery -Location 'https://www.powersh ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (https://www.pow...ery.com/api/v2/:String) [Register-PackageSource], Exception
    + FullyQualifiedErrorId : ParameterIsNotAllowedWithPSGallery,Add-PackageSource,Microsoft.PowerShell.PackageManagement.Cmdlets.RegisterPackageSource
 
PackageManagement\Find-Package : No match was found for the specified search criteria and module name 'ezlog'. Try Get-PSRepository to see all available registered module 
repositories.
At /usr/local/microsoft/powershell/6.0.0-alpha.14/Modules/PowerShellGet/1.1.2.0/PSModule.psm1:1397 char:3
+         PackageManagement\Find-Package @PSBoundParameters | Microsoft ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage
 
PackageManagement\Get-PackageSource : Unable to find repository 'PSGallery'. Use Get-PSRepository to see all available repositories.
At /usr/local/microsoft/powershell/6.0.0-alpha.14/Modules/PowerShellGet/1.1.2.0/PSModule.psm1:4489 char:35
+ ... ckageSources = PackageManagement\Get-PackageSource @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...etPackageSource:GetPackageSource) [Get-PackageSource], Exception
    + FullyQualifiedErrorId : SourceNotFound,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackageSource
 
Get-PSGalleryApiAvailability : PowerShell Gallery is currently unavailable.  Please try again later.
At /usr/local/microsoft/powershell/6.0.0-alpha.14/Modules/PowerShellGet/1.1.2.0/PSModule.psm1:4475 char:9
+         Get-PSGalleryApiAvailability -Repository $Name
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PSGalleryApiAvailability], InvalidOperationException
    + FullyQualifiedErrorId : PowerShellGalleryUnavailable,Get-PSGalleryApiAvailability
 
New-Object : Exception calling ".ctor" with "0" argument(s): "The type initializer for 'System.Net.Http.CurlHandler' threw an exception."
At /usr/local/microsoft/powershell/6.0.0-alpha.14/Modules/PowerShellGet/1.1.2.0/PSModule.psm1:6312 char:24
+             $handler = New-Object System.Net.Http.HttpClientHandler
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
 
New-Object : Exception calling ".ctor" with "0" argument(s): "The type initializer for 'System.Net.Http.CurlHandler' threw an exception."
At /usr/local/microsoft/powershell/6.0.0-alpha.14/Modules/PowerShellGet/1.1.2.0/PSModule.psm1:6312 char:24
+             $handler = New-Object System.Net.Http.HttpClientHandler
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
 
Unable to find type [Microsoft.PowerShell.Commands.PowerShellGet.Telemetry].
At /usr/local/microsoft/powershell/6.0.0-alpha.14/Modules/PowerShellGet/1.1.2.0/PSModule.psm1:715 char:26
+ ... yMethods = ([Microsoft.PowerShell.Commands.PowerShellGet.Telemetry] | ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...llGet.Telemetry:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 

```
3.
4.

## Your Environment

```PowerShell

> $PSVersionTable
Name                           Value                                                                                                                                            
----                           -----                                                                                                                                            
PSVersion                      6.0.0-alpha                                                                                                                                      
PSEdition                      Core                                                                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                          
BuildVersion                   3.0.0.0                                                                                                                                          
GitCommitId                    v6.0.0-alpha.14                                                                                                                                  
CLRVersion                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                              
PSRemotingProtocolVersion      2.3                                                                                                                                              
SerializationVersion           1.1.0.1    

> Get-Module
ModuleType Version    Name                                ExportedCommands                                                                                                      
---------- -------    ----                                ----------------                                                                                                      
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty...}                                                       
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                             
Script     1.1.2.0    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider...}                                             
Script     1.1.2.0    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}                                                 
Script     1.2        PSReadLine                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSReadlineKeyHandler, Set-PSReadlineKeyHandler...}            


> Get-Module -ListAvailable PowerShellGet,PackageManagement

    Directory: /usr/local/microsoft/powershell/6.0.0-alpha.14/Modules


ModuleType Version    Name                                ExportedCommands                                                                                                      
---------- -------    ----                                ----------------                                                                                                      
Script     1.1.2.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}                                                
Script     1.1.2.0    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}                                                          

> Get-PackageProvider

Name                     Version          DynamicOptions                                                                                                              
----                     -------          --------------                                                                                                              
NuGet                    2.8.5.208        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile...
PowerShellGet            1.1.2.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, Filter, Tag, Inclu...

> Get-PackageProvider -ListAvailable

Name                     Version          DynamicOptions                                                                                                              
----                     -------          --------------                                                                                                              
NuGet                    2.8.5.208        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile...
PowerShellGet            1.1.2.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, Filter, Tag, Inclu...

PS /Users/admin> gci env:                                                                                                                                              

Name                           Value                                                                                                                                  
----                           -----                                                                                                                                  
_                              /usr/local/bin/powershell                                                                                                              
__CF_USER_TEXT_ENCODING        0x1F5:0x0:0x1                                                                                                                          
Apple_PubSub_Socket_Render     /private/tmp/com.apple.launchd.p7yGO979tI/Render                                                                                       
HOME                           /Users/admin                                                                                                                           
LANG                           fr_FR.UTF-8                                                                                                                            
LOGNAME                        admin                                                                                                                                  
PATH                           /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin                                                                                           
PSMODULEPATH                   /Users/admin/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/usr/local/microsoft/powershell/6.0.0-alpha.14/Modules
PWD                            /Users/admin                                                                                                                           
SECURITYSESSIONID              186a7                                                                                                                                  
SHELL                          /bin/bash                                                                                                                              
SHLVL                          1                                                                                                                                      
SSH_AUTH_SOCK                  /private/tmp/com.apple.launchd.54U5qdHBcb/Listeners                                                                                    
TERM                           xterm-256color                                                                                                                         
TERM_PROGRAM                   Apple_Terminal                                                                                                                         
TERM_PROGRAM_VERSION           377                                                                                                                                    
TERM_SESSION_ID                3FB7A507-8B45-4AE7-BE0C-266691651065                                                                                                   
TMPDIR                         /var/folders/00/zg8cy1q539s636z4lvqv2b3w0000gn/T/                                                                                      
USER                           admin                                                                                                                                  
XPC_FLAGS                      0x0                                                                                                                                    
XPC_SERVICE_NAME               0                                                                                                                                      


PS /Users/admin> Get-Variable                                                                                                                                          

Name                           Value                                                                                                                                  
----                           -----                                                                                                                                  
?                              True                                                                                                                                   
^                              gci                                                                                                                                    
$                              env:                                                                                                                                   
args                           {}                                                                                                                                     
ConfirmPreference              High                                                                                                                                   
ConsoleFileName                                                                                                                                                       
DebugPreference                SilentlyContinue                                                                                                                       
Error                          {Unable to find package source 'https://www.powershellgallery.com/api/v2/'. Use Get-PackageSource to see all available package sourc...
ErrorActionPreference          Continue                                                                                                                               
ErrorView                      NormalView                                                                                                                             
ExecutionContext               System.Management.Automation.EngineIntrinsics                                                                                          
false                          False                                                                                                                                  
FormatEnumerationLimit         4                                                                                                                                      
HOME                           /Users/admin                                                                                                                           
Host                           System.Management.Automation.Internal.Host.InternalHost                                                                                
InformationPreference          SilentlyContinue                                                                                                                       
input                          System.Collections.ArrayList+ArrayListEnumeratorSimple                                                                                 
IsCoreCLR                      True                                                                                                                                   
IsLinux                        False                                                                                                                                  
IsOSX                          True                                                                                                                                   
IsWindows                      False                                                                                                                                  
LASTEXITCODE                   0                                                                                                                                      
MaximumHistoryCount            4096                                                                                                                                   
MyInvocation                   System.Management.Automation.InvocationInfo                                                                                            
NestedPromptLevel              0                                                                                                                                      
null                                                                                                                                                                  
OutputEncoding                 System.Text.ASCIIEncoding                                                                                                              
PID                            8710                                                                                                                                   
PROFILE                        /Users/admin/.config/powershell/Microsoft.PowerShell_profile.ps1                                                                       
ProgressPreference             Continue                                                                                                                               
PSBoundParameters              {}                                                                                                                                     
PSCommandPath                                                                                                                                                         
PSCulture                      fr-FR                                                                                                                                  
PSDefaultParameterValues       {}                                                                                                                                     
PSEdition                      Core                                                                                                                                   
PSEmailServer                                                                                                                                                         
PSHOME                         /usr/local/microsoft/powershell/6.0.0-alpha.14                                                                                         
PSScriptRoot                                                                                                                                                          
PSSessionApplicationName       wsman                                                                                                                                  
PSSessionConfigurationName     http://schemas.microsoft.com/powershell/Microsoft.PowerShell                                                                           
PSSessionOption                System.Management.Automation.Remoting.PSSessionOption                                                                                  
PSUICulture                    fr-FR                                                                                                                                  
PSVersionTable                 {PSVersion, PSEdition, PSCompatibleVersions, BuildVersion...}                                                                          
PWD                            /Users/admin                                                                                                                           
ShellId                        Microsoft.PowerShell                                                                                                                   
StackTrace                        at Interop.CryptoInitializer.EnsureOpenSslInitialized()...                                                                          
true                           True                                                                                                                                   
VerbosePreference              SilentlyContinue                                                                                                                       
WarningPreference              Continue                                                                                                                               
WhatIfPreference               False                                                                                                                                  


```

**Comment by bmanikm** [comment]
@apetitjean As you mentioned in the PSMVP discussion list, this issue was happening due to broken OpenSSL on your Mac. 

If anyone encounter this issue, please run below on your Mac:
**xcode-select --install
brew install openssl**
